name: データの追加
description: データを追加する際に使用するテンプレートです。
title: "Add day-data"
labels: "AddDayData"

body:
  - type: markdown
    attributes:
      value: |
        ## データの追加
        以下のフォーマットで日付、機種、投資額、回収額を入力してください。
        [日付(YYYY-MM-DD)],[機種名],[投資額(数値)],[回収額(数値)]
        ### 例
        2025-01-01,ジャグラー,1000,1000

  - type: textarea
    id: additional_datas
    attributes:
      label: 追加データリスト
      placeholder: |
        [日付(YYYY-MM-DD)],[機種名],[投資額(数値)],[回収額(数値)]
    validations:
      required: true
