name: Data Processing and Deploy

# ワークフローを実行するトリガーを定義
on:
  # mainブランチにプッシュがあった時に実行
  push:
    branches:
      - main
    paths:
      - 'data/day_datas.csv'
      - '**.py' 
      - '**.js'
      - '**.html'
      - '**.css'
  # 任意のタイミングで手動実行を可能にする
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # 2. Python環境をセットアップ (3.11を使用)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      # 3. 必要なライブラリをインストール
      # (PandasやMatplotlibなど、スクリプトで使うライブラリを記述)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib japanize_matplotlib
          
      # 4. 収支データを処理・集計するPythonスクリプトを実行
      - name: Run data aggregation scripts
        run: |
          python sorting.py
          python summary_data.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./"

  # デプロイ
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
          
      # 5. 生成された静的ファイルをGitHub Pagesにデプロイ
      # (pagesブランチを使用する標準的なデプロイ設定を想定)
      # - name: Deploy to GitHub Pages
      #   uses: peaceiris/actions-gh-pages@v4
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}
      #     # デプロイするフォルダを指定 (HTMLファイルや処理結果の静的ファイルがある場所)
      #     publish_dir: ./
      #     # デプロイ先のブランチ名
      #     publish_branch: gh-pages