name: Data Processing and Deploy

# ワークフローを実行するトリガーを定義
on:
  # イシューに投稿された時に実行
  issues:
    types: [opened]
  # 任意のタイミングで手動実行を可能にする
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  issues: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # リポジトリをチェックアウト
      - name: Checkout repository
        uses: actions/checkout@v4
        
      # Python環境をセットアップ (3.11を使用)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      # 必要なライブラリをインストール
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas matplotlib japanize_matplotlib pygithub

      # Issueからデータを読み取り、csvへ保存する
      - name: Extract Issue message
        id: extract_message
        if: ${{ github.event_name == 'issues' }}
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_NUMBER: ${{ github.event.issue.number }}
          ISSUE_TITLE: ${{ github.event.issue.title }}
          ISSUE_BODY: ${{ github.event.issue.body }}
          REPO_OWNER: ${{ github.repository_owner }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: python scripts/process_request.py
          
      # 収支データを処理・集計するPythonスクリプトを実行
      - name: Run data aggregation scripts
        run: |
          python scripts/create_namelist.py
          python scripts/sorting.py
          python scripts/summary_data.py
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './'
      # 変更があるかどうかを判定
      - name: Check for change
        # git status --porcelainで変更されたファイルの一覧を取得
        # 変更がなければこの結果は空になる
        run: |
          if [[ -z $(git status --porcelain) ]]; then
            echo "COMMIT_NEEDED=false" >> $GITHUB_ENV
            echo "No changes detected. Skipping commit."
          else
            echo "COMMIT_NEEDED=true" >> $GITHUB_ENV
            echo "Changes detected. Proceeding to commit."
          fi
      # 変更内容をブランチに反映する(Issue以外からのトリガー)
      - name: commit change(not issue trigger)
        if: ${{ (github.event_name != 'issues') && (env.COMMIT_NEEDED == 'true') }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update all with GitHub Actions"
          git push
      # 変更内容をブランチに反映する(Issueからのトリガー)
      - name: commit change(issue trigger)
        if: ${{ (github.event_name == 'issues') && (env.COMMIT_NEEDED == 'true') }}
        env:
          ISSUE_NUMBER: ${{ github.event.issue.number }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "update all with GitHub Actions close #${ISSUE_NUMBER}"
          git push

  # デプロイ
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4